#cloud-config

users:
  - name: sui
    groups: [users, admin]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]

packages:
  - tzdata
  - libprotobuf-dev
  - ca-certificates
  - build-essential
  - libssl-dev
  - libclang-dev
  - pkg-config
  - openssl
  - protobuf-compiler
  - git
  - clang
  - cmake
  - git-all
  - gcc
  - libpq-dev

runcmd:
  - echo 'Installing Google Cloud Ops Agent...'
  - curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
  - sudo bash add-google-cloud-ops-agent-repo.sh --also-install

  # Configure Ops Agent to pipe Sui metrics into Cloud Monitoring
  - |
    sudo bash -c 'cat << EOF > /etc/google-cloud-ops-agent/config.yaml
    metrics:
      receivers:
        prometheus:
          type: prometheus
          config:
            scrape_configs:
              - job_name: 'sui-metrics'
                static_configs:
                  - targets: ['localhost:9184']
                scrape_interval: 30s
      service:
        pipelines:
          default_pipeline:
            receivers: [prometheus]
    EOF'

  # Restart Ops Agent to apply changes
  - sudo service google-cloud-ops-agent restart
  - echo "Ops Agent installation complete."
  - mkdir -p /opt/sui/bin
  - mkdir -p /opt/sui/config
  - mkdir -p /opt/sui/db
  - mkdir -p /opt/sui/key-pairs
  - chown -R sui:sui /opt/sui
  - curl -fsSL https://get.docker.com | sh
  - usermod -aG docker sui
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> /home/sui/.bashrc
  - wget -P /opt/sui/config https://github.com/MystenLabs/sui-genesis/raw/main/mainnet/genesis.blob
  - wget -O /opt/sui/config/fullnode.yaml https://github.com/MystenLabs/sui/raw/main/crates/sui-config/data/fullnode-template.yaml
  - wget -P /opt/sui/bin/ https://releases.sui.io/115117180263c8bc25190ce76b6cbe2114551f7c/sui-node
  - chown -R sui:sui /opt/sui
  - chmod 544 /opt/sui/bin/sui-node
